deploy32

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,15 +51,25 @@ jobs:
         run: terraform apply PLAN
         working-directory: ./terraform
 
-      - name: Set output
+      - name: Get Public IP
         id: set_ip
         run: |-
-          echo "::set-output name=instance_public_ip::$(terraform output instance_public_ip)"
+          INSTANCE_IP=$(terraform output -raw instance_public_ip 2>/dev/null || echo "")
+          if [[ -z "$INSTANCE_IP" ]]; then
+            echo "Error: No public IP found!" >&2
+            exit 1
+          fi
+          echo "Instance Public IP: $INSTANCE_IP"
+          echo "INSTANCE_PUBLIC_IP=$INSTANCE_IP" >> $GITHUB_ENV
+          echo "::set-output name=instance_public_ip::$INSTANCE_IP"
 
   deploy-app:
     runs-on: ubuntu-latest
     needs: deploy-infra
     steps:
+      - name: Debug Server Public IP
+        run: echo "SERVER_PUBLIC_IP=${{ needs.deploy-infra.outputs.SERVER_PUBLIC_IP }}"
+
       - name: Checkout
         uses: actions/checkout@v3
       - name: Set IMAGE variable
@@ -86,7 +96,7 @@ jobs:
           AWS_DEFAULT_REGION: us-east-1
         uses: appleboy/ssh-action@master
         with:
-          host: ${{ needs.deploy-infra.outputs.SERVER_PUBLIC_IP }}
+          host: ${{ env.SERVER_PUBLIC_IP }}
           username: ubuntu
           key: ${{ env.SSH_KEY_PRIVATE }}
           envs: SSH_KEY_PRIVATE,REGISTRY,REPOSITORY,IMAGE,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
@@ -99,3 +109,4 @@ jobs:
             sudo docker rm myappcontainer || true
             sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE
             sudo docker run -d --name myappcontainer -p 80:8080 $REGISTRY/$REPOSITORY:$IMAGE
+
