deploy29

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,10 +51,17 @@ jobs:
         run: terraform apply PLAN
         working-directory: ./terraform
 
-      - name: Set output
+      - name: Get EC2 Public IP
         id: set_ip
-        run: |-
-          echo "::set-output name=instance_public_ip::$(terraform output instance_public_ip)"
+        run: |
+          INSTANCE_IP=$(terraform output -raw instance_public_ip 2>/dev/null || echo "")
+          if [[ -z "$INSTANCE_IP" ]]; then
+            echo "Error: No public IP found!" >&2
+            exit 1
+          fi
+          echo "INSTANCE_PUBLIC_IP=$INSTANCE_IP" >> $GITHUB_ENV
+        working-directory: ./terraform
+      
 
   deploy-app:
     runs-on: ubuntu-latest
@@ -77,7 +84,7 @@ jobs:
         run: |-
           docker build -t $REGISTRY/$REPOSITORY:$IMAGE .
           docker push $REGISTRY/$REPOSITORY:$IMAGE
-        working-directory: ./terraform
+        working-directory: ./node-app
       - name: Deploy docker image to ec2
         env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
